title: Awesomee titleeee
email: lucascebrero@gmail.com
description: >-
       Personal website 
baseurl: ""
url: ""
twitter_username: lucascebrero
github_username: lucascebrero

# Build settings
markdown: kramdown

